server:
  port: 8080
eureka: 
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:${server.port}/eureka/
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routers:
        - id: ms-usuario
          uri: lb://ms-usuario
          predicates:
            - Path=/usuario/**
        - id: ms-habilidades
          uri: lb://ms-habilidades
          predicates:
            - Path=/ms-habilidades/**
        - id: ms-experiencias
          uri: lb://ms-experiencias
          predicates:
            - Path=/ms-experiencias/**